package cli

import (
	"fmt"
	"io"
	"regexp"
	"strings"
)

// Shell completion scripts are generated from the option table:
// `TOOL --help-completion=bash|zsh|fish`.

// argKind says how an option's value completes.
type argKind int

const (
	argNone   argKind = iota // boolean option
	argFree                  // a value with no completion
	argFile                  // a file name
	argDir                   // a directory name
	argValues                // one of a fixed list
)

var enumArg = regexp.MustCompile(`^[a-z]+(\|[a-z]+)+$`)

// kind classifies an option's value and returns the fixed values, if any.
func (o *opt) kind() (argKind, []string) {
	switch {
	case o.argName == "":
		return argNone, nil
	case o.long == "jobs":
		return argValues, []string{"max", "1", "2", "4", "8", "16"}
	case o.long == "progress":
		return argValues, []string{"always", "never", "auto"}
	case o.argName == "DIR":
		return argDir, nil
	case strings.Contains(o.argName, "FILE") || o.argName == "PATH" || o.argName == "PREFIX" ||
		o.argName == "TABLE" || o.argName == "TAXONOMY" || strings.HasSuffix(o.argName, ".json"):
		return argFile, nil
	case enumArg.MatchString(o.argName):
		return argValues, strings.Split(o.argName, "|")
	}
	return argFree, nil
}

func (p *Parser) visible() []*opt {
	var out []*opt
	for _, o := range p.opts {
		if o.help != "" {
			out = append(out, o)
		}
	}
	return out
}

// Completion writes the completion script for shell.
func (p *Parser) Completion(w io.Writer, shell string) error {
	switch shell {
	case "bash":
		p.bashCompletion(w)
	case "zsh":
		p.zshCompletion(w)
	case "fish":
		p.fishCompletion(w)
	default:
		return fmt.Errorf("--help-completion: want bash, zsh or fish, got %q", shell)
	}
	return nil
}

func funcName(prog string) string {
	return "_grev_" + strings.NewReplacer("-", "_", ".", "_").Replace(prog)
}

func (p *Parser) bashCompletion(w io.Writer) {
	fn := funcName(p.Prog)
	var words []string
	byKind := map[argKind][]string{}
	var values []string // case arms for fixed-value options
	for _, o := range p.visible() {
		k, vals := o.kind()
		var names []string
		if o.short != 0 {
			names = append(names, "-"+string(o.short))
		}
		if o.long != "" {
			names = append(names, "--"+o.long)
		}
		words = append(words, names...)
		if k == argNone {
			continue
		}
		if o.optional { // only --long=VALUE takes a value
			names = []string{"--" + o.long}
		}
		if k == argValues {
			values = append(values, fmt.Sprintf("        %s) COMPREPLY=($(compgen -W '%s' -- \"$cur\")); return ;;",
				strings.Join(names, "|"), strings.Join(vals, " ")))
			continue
		}
		byKind[k] = append(byKind[k], names...)
	}
	fmt.Fprintf(w, "# bash completion for %s                                   -*- shell-script -*-\n", p.Prog)
	fmt.Fprintf(w, "# Generated by %s --help-completion=bash; do not edit.\n\n", p.Prog)
	fmt.Fprintf(w, "%s() {\n", fn)
	fmt.Fprintln(w, `    local cur=${COMP_WORDS[COMP_CWORD]} prev=${COMP_WORDS[COMP_CWORD-1]}`)
	fmt.Fprintln(w, `    if [[ $prev == = && $COMP_CWORD -ge 2 ]]; then`)
	fmt.Fprintln(w, `        prev=${COMP_WORDS[COMP_CWORD-2]}`)
	fmt.Fprintln(w, `    elif [[ $cur == = ]]; then`)
	fmt.Fprintln(w, `        cur=''`)
	fmt.Fprintln(w, `    fi`)
	fmt.Fprintln(w, `    case $prev in`)
	for _, v := range values {
		fmt.Fprintln(w, v)
	}
	if n := byKind[argFile]; len(n) > 0 {
		fmt.Fprintf(w, "        %s) COMPREPLY=($(compgen -f -- \"$cur\")); return ;;\n", strings.Join(n, "|"))
	}
	if n := byKind[argDir]; len(n) > 0 {
		fmt.Fprintf(w, "        %s) COMPREPLY=($(compgen -d -- \"$cur\")); return ;;\n", strings.Join(n, "|"))
	}
	if n := byKind[argFree]; len(n) > 0 {
		fmt.Fprintf(w, "        %s) return ;;\n", strings.Join(n, "|"))
	}
	fmt.Fprintln(w, `    esac`)
	fmt.Fprintln(w, `    if [[ $cur == -* ]]; then`)
	fmt.Fprintf(w, "        COMPREPLY=($(compgen -W '%s' -- \"$cur\"))\n", strings.Join(words, " "))
	fmt.Fprintln(w, `        return`)
	fmt.Fprintln(w, `    fi`)
	if len(p.Commands) > 0 {
		fmt.Fprintf(w, "    COMPREPLY=($(compgen -W '%s' -- \"$cur\") $(compgen -f -- \"$cur\"))\n", strings.Join(p.Commands, " "))
	} else {
		fmt.Fprintln(w, `    COMPREPLY=($(compgen -f -- "$cur"))`)
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintf(w, "complete -o filenames -F %s %s\n", fn, p.Prog)
}

// zshDesc escapes an option description (inside [...]) for an _arguments
// spec, which itself sits in single quotes.
func zshDesc(s string) string {
	return strings.NewReplacer(`\`, `\\`, `[`, `\[`, `]`, `\]`, `'`, `'\''`).Replace(s)
}

// zshMsg escapes the message field of an argument spec (colons separate
// fields there).
func zshMsg(s string) string {
	return strings.NewReplacer(`\`, `\\`, `'`, `'\''`, ":", `\:`).Replace(s)
}

func (p *Parser) zshCompletion(w io.Writer) {
	fmt.Fprintf(w, "#compdef %s\n", p.Prog)
	fmt.Fprintf(w, "# zsh completion for %s. Generated by %s --help-completion=zsh; do not edit.\n\n", p.Prog, p.Prog)
	fmt.Fprintln(w, "_arguments -s -S \\")
	for _, o := range p.visible() {
		k, vals := o.kind()
		desc := "[" + zshDesc(o.help) + "]"
		msg := zshMsg(o.argName)
		var action string
		switch k {
		case argFile:
			action = ":" + msg + ":_files"
		case argDir:
			action = ":" + msg + ":_files -/"
		case argValues:
			action = ":" + msg + ":(" + strings.Join(vals, " ") + ")"
		case argFree:
			action = ":" + msg + ":"
		}
		var specs []string
		switch {
		case k == argNone:
			if o.short != 0 {
				specs = append(specs, "-"+string(o.short)+desc)
			}
			if o.long != "" {
				specs = append(specs, "--"+o.long+desc)
			}
		case o.optional:
			if o.short != 0 {
				specs = append(specs, "-"+string(o.short)+desc)
			}
			specs = append(specs, "--"+o.long+"=-"+desc+":"+action)
		default:
			if o.short != 0 {
				specs = append(specs, "-"+string(o.short)+"+"+desc+action)
			}
			if o.long != "" {
				specs = append(specs, "--"+o.long+"="+desc+action)
			}
		}
		prefix := ""
		switch {
		case o.repeat:
			prefix = "*"
		case len(specs) > 1:
			var names []string
			if o.short != 0 {
				names = append(names, "-"+string(o.short))
			}
			if o.long != "" {
				names = append(names, "--"+o.long)
			}
			prefix = "(" + strings.Join(names, " ") + ")"
		}
		for _, s := range specs {
			fmt.Fprintf(w, "  '%s%s' \\\n", prefix, s)
		}
	}
	if len(p.Commands) > 0 {
		fmt.Fprintf(w, "  '1:command:(%s)' \\\n", strings.Join(p.Commands, " "))
	}
	fmt.Fprintln(w, "  '*:file:_files'")
}

// fishQuote single-quotes s for fish.
func fishQuote(s string) string {
	return "'" + strings.NewReplacer(`\`, `\\`, `'`, `\'`).Replace(s) + "'"
}

func (p *Parser) fishCompletion(w io.Writer) {
	fmt.Fprintf(w, "# fish completion for %s. Generated by %s --help-completion=fish; do not edit.\n", p.Prog, p.Prog)
	if len(p.Commands) > 0 {
		fmt.Fprintf(w, "complete -c %s -n __fish_use_subcommand -f -a %s\n", p.Prog, fishQuote(strings.Join(p.Commands, " ")))
	}
	for _, o := range p.visible() {
		k, vals := o.kind()
		line := "complete -c " + p.Prog
		if o.short != 0 {
			line += " -s " + string(o.short)
		}
		if o.long != "" {
			line += " -l " + o.long
		}
		switch {
		case k == argNone || o.optional:
		case k == argFile || k == argDir:
			line += " -r -F"
		case k == argValues:
			line += " -x -a " + fishQuote(strings.Join(vals, " "))
		default:
			line += " -x"
		}
		line += " -d " + fishQuote(o.help)
		fmt.Fprintln(w, line)
	}
}
